limit_req_zone $binary_remote_addr zone=mare_requests:10m rate=10r/s;
server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    server_tokens off;
    client_max_body_size 2m;
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy same-origin always;
    add_header X-Frame-Options DENY always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; font-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'" always;
    location /api/ {
        limit_req zone=mare_requests burst=40 nodelay;
        proxy_pass http://api:8000;
        proxy_set_header Host api;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 65s;
    }
    location /health/ {
        proxy_pass http://api:8000;
        proxy_set_header Host api;
    }
    location /assets/ { try_files $uri =404; expires 1y; }
    location / { try_files $uri $uri/ /index.html; }
}
