"""Initial web persistence"""

from alembic import op
import sqlalchemy as sa

revision = "0001_web"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("target_rounds", sa.Integer(), nullable=False),
        sa.Column("current_round", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("lease_token", sa.String(length=50), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_runs_status"), "runs", ["status"], unique=False)
    op.create_table(
        "branches",
        sa.Column("run_id", sa.String(length=50), nullable=False),
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id", "id"),
    )
    op.create_index(op.f("ix_branches_status"), "branches", ["status"], unique=False)
    op.create_table(
        "claims",
        sa.Column("run_id", sa.String(length=50), nullable=False),
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id", "id"),
    )
    op.create_index(op.f("ix_claims_status"), "claims", ["status"], unique=False)
    op.create_table(
        "dependencies",
        sa.Column("run_id", sa.String(length=50), nullable=False),
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("parent_id", sa.String(length=50), nullable=False),
        sa.Column("child_id", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id", "id"),
    )
    op.create_table(
        "evidence",
        sa.Column("run_id", sa.String(length=50), nullable=False),
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("claim_id", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id", "id"),
    )
    op.create_index(op.f("ix_evidence_claim_id"), "evidence", ["claim_id"], unique=False)
    op.create_table(
        "failures",
        sa.Column("run_id", sa.String(length=50), nullable=False),
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id", "id"),
    )
    op.create_table(
        "questions",
        sa.Column("run_id", sa.String(length=50), nullable=False),
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id", "id"),
    )
    op.create_index(op.f("ix_questions_status"), "questions", ["status"], unique=False)
    op.create_table(
        "run_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=50), nullable=False),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_events_run_cursor", "run_events", ["run_id", "id"], unique=False)
    op.create_index(op.f("ix_run_events_run_id"), "run_events", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_run_events_run_id"), table_name="run_events")
    op.drop_index("ix_events_run_cursor", table_name="run_events")
    op.drop_table("run_events")
    op.drop_index(op.f("ix_questions_status"), table_name="questions")
    op.drop_table("questions")
    op.drop_table("failures")
    op.drop_index(op.f("ix_evidence_claim_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_table("dependencies")
    op.drop_index(op.f("ix_claims_status"), table_name="claims")
    op.drop_table("claims")
    op.drop_index(op.f("ix_branches_status"), table_name="branches")
    op.drop_table("branches")
    op.drop_index(op.f("ix_runs_status"), table_name="runs")
    op.drop_table("runs")
    # ### end Alembic commands ###
