/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config */
        get: operations["config_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_api_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Branches */
        get: operations["list_branches_api_runs__run_id__branches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Claims */
        get: operations["list_claims_api_runs__run_id__claims_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence */
        get: operations["list_evidence_api_runs__run_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/failures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Failures */
        get: operations["list_failures_api_runs__run_id__failures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Questions */
        get: operations["list_questions_api_runs__run_id__questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Graph */
        get: operations["graph_api_runs__run_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream */
        get: operations["stream_api_runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssumptionAudit */
        AssumptionAudit: {
            /** Id */
            id: string;
            /** Claim Id */
            claim_id: string;
            status: components["schemas"]["AuditStatus"];
            /** Extra Assumptions */
            extra_assumptions: string[];
            /** Matched Problem Constraints */
            matched_problem_constraints: string[];
            /** Violations */
            violations: string[];
            /**
             * Notes
             * @default
             */
            notes: string;
            /**
             * Auditor
             * @default assumption-firewall
             */
            auditor: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * AuditStatus
         * @enum {string}
         */
        AuditStatus: "pass" | "warn" | "block";
        /** Branch */
        Branch: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Research Question */
            research_question: string;
            /** Strategy */
            strategy: string;
            /** Parent Id */
            parent_id: string | null;
            /** @default active */
            status: components["schemas"]["BranchStatus"];
            /**
             * Score
             * @default 0.5
             */
            score: number;
            /**
             * Compute Spent
             * @default 0
             */
            compute_spent: number;
            /**
             * Verified Progress
             * @default 0
             */
            verified_progress: number;
            /**
             * Novelty
             * @default 0.5
             */
            novelty: number;
            /**
             * Uncertainty
             * @default 1
             */
            uncertainty: number;
            /**
             * Consecutive Low Score Rounds
             * @default 0
             */
            consecutive_low_score_rounds: number;
            /**
             * Created Round
             * @default 0
             */
            created_round: number;
            /**
             * Heuristic Score
             * @default 0.5
             */
            heuristic_score: number;
            /** Policy Score */
            policy_score: number | null;
            /**
             * Policy Blend
             * @default 0
             */
            policy_blend: number;
        };
        /**
         * BranchStatus
         * @enum {string}
         */
        BranchStatus: "active" | "promising" | "deprioritized" | "terminated" | "solved";
        /** Claim */
        Claim: {
            /** Id */
            id: string;
            /** Branch Id */
            branch_id: string;
            /** Statement */
            statement: string;
            /** Claim Type */
            claim_type: string;
            /** Derivation */
            derivation: string;
            /** Assumptions */
            assumptions: string[];
            /** Dependencies */
            dependencies: string[];
            /** Suggested Checks */
            suggested_checks: string[];
            /** Tags */
            tags: string[];
            /** @default local_lemma */
            scope: components["schemas"]["ClaimScope"];
            /** Extra Assumptions */
            extra_assumptions: string[];
            /** Formal Statement */
            formal_statement: string | null;
            /** @default proposed */
            status: components["schemas"]["ClaimStatus"];
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /** Created By */
            created_by: string;
            /** Round No */
            round_no: number;
            /** Question Id */
            question_id: string | null;
        };
        /**
         * ClaimScope
         * @enum {string}
         */
        ClaimScope: "local_lemma" | "restricted_result" | "root_candidate";
        /** ClaimSourceLink */
        ClaimSourceLink: {
            /** Id */
            id: string;
            /** Claim Id */
            claim_id: string;
            /** Source Id */
            source_id: string;
            /**
             * Relation
             * @default relevant
             * @enum {string}
             */
            relation: "relevant" | "supports" | "contradicts" | "background";
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * ClaimStatus
         * @enum {string}
         */
        ClaimStatus: "proposed" | "contested" | "survived_review" | "verified" | "rejected" | "formalized" | "scope_blocked";
        /** CreateRun */
        CreateRun: {
            /**
             * Title
             * @default Burgers gradient blow-up
             */
            title: string;
            /**
             * Provider
             * @default mock
             * @enum {string}
             */
            provider: "mock" | "openai";
            /** Statement */
            statement?: string | null;
            /** Assumptions */
            assumptions?: string[];
            /** Success Conditions */
            success_conditions?: string[];
            /**
             * Rounds
             * @default 2
             */
            rounds: number;
            /**
             * Policy
             * @default hybrid
             * @enum {string}
             */
            policy: "hybrid" | "heuristic";
            /**
             * Max Model Calls
             * @default 250
             */
            max_model_calls: number;
            /**
             * Max Reserved Output Tokens
             * @default 1000000
             */
            max_reserved_output_tokens: number;
            /**
             * Max Tool Calls
             * @default 2000
             */
            max_tool_calls: number;
        };
        /** DependencyEdge */
        DependencyEdge: {
            /** Id */
            id: string;
            /** Parent Claim Id */
            parent_claim_id: string;
            /** Child Claim Id */
            child_claim_id: string;
            /**
             * Relation
             * @default requires
             * @enum {string}
             */
            relation: "requires" | "supports" | "contradicts";
            /**
             * Created Round
             * @default 0
             */
            created_round: number;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** EventOut */
        EventOut: {
            /** Id */
            id: number;
            /** Run Id */
            run_id: string;
            /** Kind */
            kind: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Evidence */
        Evidence: {
            /** Id */
            id: string;
            /** Claim Id */
            claim_id: string;
            /**
             * Evidence Type
             * @enum {string}
             */
            evidence_type: "symbolic" | "numerical" | "citation" | "independent_derivation" | "counterexample_search" | "formal_proof" | "adversarial_review" | "scope_audit";
            result: components["schemas"]["EvidenceResult"];
            /** Verifier */
            verifier: string;
            /**
             * Reproducible
             * @default true
             */
            reproducible: boolean;
            /**
             * Details
             * @default
             */
            details: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /**
         * EvidenceResult
         * @enum {string}
         */
        EvidenceResult: "supports" | "contradicts" | "inconclusive";
        /** Failure */
        Failure: {
            /** Id */
            id: string;
            /** Branch Id */
            branch_id: string;
            /** Failed Claim Id */
            failed_claim_id: string | null;
            /** Mechanism */
            mechanism: string;
            /** Failure Reason */
            failure_reason: string;
            /** Reusable Constraint */
            reusable_constraint: string | null;
            /**
             * Severity
             * @default major
             * @enum {string}
             */
            severity: "minor" | "major" | "fatal";
            /** Tags */
            tags: string[];
            /**
             * Created Round
             * @default 0
             */
            created_round: number;
        };
        /** FormalizationRecord */
        FormalizationRecord: {
            /** Id */
            id: string;
            /** Claim Id */
            claim_id: string;
            status: components["schemas"]["FormalizationStatus"];
            /** Prover */
            prover: string;
            /**
             * Source Code
             * @default
             */
            source_code: string;
            /**
             * Stdout
             * @default
             */
            stdout: string;
            /**
             * Stderr
             * @default
             */
            stderr: string;
            /**
             * Elapsed Ms
             * @default 0
             */
            elapsed_ms: number;
            /** Artifact Path */
            artifact_path: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * FormalizationStatus
         * @enum {string}
         */
        FormalizationStatus: "queued" | "passed" | "failed" | "skipped";
        /** GraphNode */
        GraphNode: {
            /** Id */
            id: string;
            /** Statement */
            statement: string;
            /** Status */
            status: string;
            /** Completeness */
            completeness: number;
        };
        /** GraphResponse */
        GraphResponse: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["DependencyEdge"][];
            /** Has Cycle */
            has_cycle: boolean;
            /** Candidate Roots */
            candidate_roots: string[];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** ModelInvocation */
        ModelInvocation: {
            /** Id */
            id: string;
            /** Provider */
            provider: string;
            /** Model */
            model: string | null;
            /** Schema Name */
            schema_name: string;
            /** System Hash */
            system_hash: string;
            /** Prompt Hash */
            prompt_hash: string;
            /** Max Tokens */
            max_tokens: number;
            /** Temperature */
            temperature: number;
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Success */
            success: boolean;
            /** Error */
            error: string | null;
            /** Input Tokens */
            input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** Objection */
        Objection: {
            /** Id */
            id: string;
            /** Claim Id */
            claim_id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "minor" | "major" | "fatal";
            /** Description */
            description: string;
            /**
             * Resolved
             * @default false
             */
            resolved: boolean;
            /**
             * Created By
             * @default assassin
             */
            created_by: string;
        };
        /** PolicyExample */
        PolicyExample: {
            /** Id */
            id: string;
            kind: components["schemas"]["PolicyExampleKind"];
            /** Round No */
            round_no: number;
            /** Object Id */
            object_id: string;
            /** Features */
            features: number[];
            /** Target */
            target: number | null;
            /** Finalized Round */
            finalized_round: number | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /**
         * PolicyExampleKind
         * @enum {string}
         */
        PolicyExampleKind: "branch" | "question";
        /** PolicyNetworkState */
        PolicyNetworkState: {
            kind: components["schemas"]["PolicyExampleKind"];
            /** Input Size */
            input_size: number;
            /** Hidden Size */
            hidden_size: number;
            /**
             * Trained Examples
             * @default 0
             */
            trained_examples: number;
            /**
             * Epochs
             * @default 0
             */
            epochs: number;
            /** Loss */
            loss: number | null;
            /** Weights1 */
            weights1: number[][];
            /** Bias1 */
            bias1: number[];
            /** Weights2 */
            weights2: number[];
            /**
             * Bias2
             * @default 0
             */
            bias2: number;
            /**
             * Active
             * @default false
             */
            active: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProblemSpec */
        ProblemSpec: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Canonical Statement */
            canonical_statement: string;
            /** Definitions */
            definitions: string[];
            /** Assumptions */
            assumptions: string[];
            /** Success Conditions */
            success_conditions: string[];
            /** Disallowed Shortcuts */
            disallowed_shortcuts: string[];
            /** Scope Constraints */
            scope_constraints: string[];
            /** Verification Requirements */
            verification_requirements: string[];
            /** Formal Target */
            formal_target: string | null;
        };
        /**
         * QuestionStatus
         * @enum {string}
         */
        QuestionStatus: "open" | "assigned" | "answered" | "invalidated";
        /**
         * ResearchBudget
         * @description Hard research-run limits.
         *
         *     V0.3 accounts for *reserved* model output tokens because provider-independent
         *     actual token usage is not always available. Providers may additionally report
         *     actual input/output usage on ModelInvocation.
         */
        ResearchBudget: {
            /**
             * Max Model Calls
             * @default 250
             */
            max_model_calls: number;
            /**
             * Max Reserved Output Tokens
             * @default 1000000
             */
            max_reserved_output_tokens: number;
            /**
             * Max Tool Calls
             * @default 2000
             */
            max_tool_calls: number;
            /**
             * Max Rounds
             * @default 100
             */
            max_rounds: number;
            /**
             * Model Calls Used
             * @default 0
             */
            model_calls_used: number;
            /**
             * Reserved Output Tokens Used
             * @default 0
             */
            reserved_output_tokens_used: number;
            /**
             * Tool Calls Used
             * @default 0
             */
            tool_calls_used: number;
        };
        /** ResearchEvent */
        ResearchEvent: {
            /** Id */
            id: string;
            /** Event Type */
            event_type: string;
            /** Actor */
            actor: string;
            /** Round No */
            round_no: number;
            /** Object Id */
            object_id: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** ResearchPolicyState */
        ResearchPolicyState: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Hidden Size
             * @default 12
             */
            hidden_size: number;
            /**
             * Min Branch Examples
             * @default 12
             */
            min_branch_examples: number;
            /**
             * Min Question Examples
             * @default 16
             */
            min_question_examples: number;
            /**
             * Training Epochs
             * @default 220
             */
            training_epochs: number;
            /**
             * Learning Rate
             * @default 0.03
             */
            learning_rate: number;
            /**
             * L2
             * @default 0.0001
             */
            l2: number;
            /**
             * Seed
             * @default 7
             */
            seed: number;
            /**
             * Max Neural Blend
             * @default 0.65
             */
            max_neural_blend: number;
            /**
             * Blend Warmup Examples
             * @default 20
             */
            blend_warmup_examples: number;
            /** Examples */
            examples: components["schemas"]["PolicyExample"][];
            branch_network: components["schemas"]["PolicyNetworkState"] | null;
            question_network: components["schemas"]["PolicyNetworkState"] | null;
        };
        /** ResearchQuestion */
        ResearchQuestion: {
            /** Id */
            id: string;
            /** Branch Id */
            branch_id: string | null;
            /** Question */
            question: string;
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /**
             * Expected Information Gain
             * @default 0.5
             */
            expected_information_gain: number;
            /**
             * Expected Impact
             * @default 0.5
             */
            expected_impact: number;
            /**
             * Difficulty
             * @default 0.5
             */
            difficulty: number;
            /**
             * Novelty
             * @default 0.5
             */
            novelty: number;
            /**
             * Spawn New Branch
             * @default false
             */
            spawn_new_branch: boolean;
            /** Suggested Branch Title */
            suggested_branch_title: string | null;
            /** Suggested Strategy */
            suggested_strategy: string | null;
            /** @default open */
            status: components["schemas"]["QuestionStatus"];
            /**
             * Created Round
             * @default 0
             */
            created_round: number;
            /** Answered By Claim Ids */
            answered_by_claim_ids: string[];
            /** Policy Score */
            policy_score: number | null;
            /**
             * Policy Blend
             * @default 0
             */
            policy_blend: number;
        };
        /** ResearchState */
        ResearchState: {
            /** Run Id */
            run_id: string;
            problem: components["schemas"]["ProblemSpec"];
            budget: components["schemas"]["ResearchBudget"];
            policy: components["schemas"]["ResearchPolicyState"];
            /**
             * Current Round
             * @default 0
             */
            current_round: number;
            /** Branches */
            branches: components["schemas"]["Branch"][];
            /** Questions */
            questions: components["schemas"]["ResearchQuestion"][];
            /** Tasks */
            tasks: components["schemas"]["ResearchTask"][];
            /** Claims */
            claims: components["schemas"]["Claim"][];
            /** Dependency Edges */
            dependency_edges: components["schemas"]["DependencyEdge"][];
            /** Objections */
            objections: components["schemas"]["Objection"][];
            /** Failures */
            failures: components["schemas"]["Failure"][];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Sources */
            sources: components["schemas"]["SourceRecord"][];
            /** Source Links */
            source_links: components["schemas"]["ClaimSourceLink"][];
            /** Assumption Audits */
            assumption_audits: components["schemas"]["AssumptionAudit"][];
            /** Formalizations */
            formalizations: components["schemas"]["FormalizationRecord"][];
            /** Tool Invocations */
            tool_invocations: components["schemas"]["ToolInvocation"][];
            /** Invocations */
            invocations: components["schemas"]["ModelInvocation"][];
            /** Events */
            events: components["schemas"]["ResearchEvent"][];
            /** Synthesis Notes */
            synthesis_notes: string[];
        };
        /** ResearchTask */
        ResearchTask: {
            /** Id */
            id: string;
            /** Branch Id */
            branch_id: string;
            /** Title */
            title: string;
            /** Objective */
            objective: string;
            /**
             * Round No
             * @default 1
             */
            round_no: number;
            /**
             * Token Budget
             * @default 4000
             */
            token_budget: number;
            /** Question Id */
            question_id: string | null;
            /**
             * Source
             * @default director
             * @enum {string}
             */
            source: "director" | "navigator" | "question_engine" | "human" | "proof_graph";
        };
        /** RunDetail */
        RunDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "cancelling" | "cancelled" | "completed" | "failed" | "budget_exhausted";
            /** Provider */
            provider: string;
            /** Target Rounds */
            target_rounds: number;
            /** Current Round */
            current_round: number;
            /** Attempts */
            attempts: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Error */
            error: string | null;
            snapshot: components["schemas"]["ResearchState"];
        };
        /** RunSummary */
        RunSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "cancelling" | "cancelled" | "completed" | "failed" | "budget_exhausted";
            /** Provider */
            provider: string;
            /** Target Rounds */
            target_rounds: number;
            /** Current Round */
            current_round: number;
            /** Attempts */
            attempts: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Error */
            error: string | null;
        };
        /** ServiceSettings */
        ServiceSettings: {
            /** Version */
            version: string;
            /** Engine Version */
            engine_version: string;
            /** Authentication */
            authentication: string;
            /** Providers */
            providers: string[];
            /** Openai Model */
            openai_model: string | null;
            /** Max Attempts */
            max_attempts: number;
            /** Round Timeout Seconds */
            round_timeout_seconds: number;
            /** Checkpoint Boundary */
            checkpoint_boundary: string;
            /** Workspace Mode */
            workspace_mode: string;
        };
        /** SourceRecord */
        SourceRecord: {
            /** Id */
            id: string;
            /** Provider */
            provider: string;
            /** Title */
            title: string;
            /** Url */
            url: string | null;
            /** External Id */
            external_id: string | null;
            /** Authors */
            authors: string[];
            /** Year */
            year: number | null;
            /**
             * Abstract
             * @default
             */
            abstract: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** ToolInvocation */
        ToolInvocation: {
            /** Id */
            id: string;
            /** Tool */
            tool: string;
            /** Operation */
            operation: string;
            /** Claim Id */
            claim_id: string | null;
            /** Success */
            success: boolean;
            /**
             * Elapsed Ms
             * @default 0
             */
            elapsed_ms: number;
            /**
             * Details
             * @default
             */
            details: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    config_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceSettings"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRun"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    detail_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    cancel_api_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    resume_api_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_branches_api_runs__run_id__branches_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_claims_api_runs__run_id__claims_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claim"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_evidence_api_runs__run_id__evidence_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_failures_api_runs__run_id__failures_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Failure"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_questions_api_runs__run_id__questions_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchQuestion"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    graph_api_runs__run_id__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    events_api_runs__run_id__events_get: {
        parameters: {
            query?: {
                after?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    stream_api_runs__run_id__stream_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
